# Generated by Django 5.0 on 2024-04-26 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('location_ID', models.TextField(max_length=20)),
                ('product_ID', models.TextField()),
                ('quantity', models.IntegerField()),
                ('vendor', models.TextField(default=None, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('manufacturer_barcode', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('high_priority', models.BooleanField(default=False)),
                ('description', models.TextField(default='', max_length=150)),
                ('printed', models.BooleanField(default=False)),
                ('admin_field_price1', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('admin_field_price2', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
