# Generated by Django 5.0 on 2025-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_modified_by_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_barcode',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
