# Generated by Django 5.0 on 2025-05-28 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_manufacturer_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_field_price1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_field_price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
