# Generated by Django 5.0 on 2025-05-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_admin_field_price1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location_ID',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
