# Generated by Django 5.0 on 2023-12-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_field_price1',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_field_price2',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
