# Generated by Django 5.0 on 2023-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_admin_field_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_field_price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_field_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location_ID',
            field=models.TextField(max_length=20),
        ),
    ]
