# Generated by Django 5.0 on 2025-05-28 21:16
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_field_price1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_field_price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
           migrations.AlterField(
            model_name='product',
            name='location_ID',
            field=models.CharField(max_length=11, unique=True),
        ),
           migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.TextField(),  # or CharField(max_length=255) if needed
        ),
    ]
