# Generated by Django 5.0 on 2024-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_vendor_alter_product_admin_field_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
