# Generated by Django 5.0 on 2024-01-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_field_price1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_field_price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
