# Generated by Django 5.0 on 2025-06-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_product_max_quantity_product_min_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modified_by',
        ),
    ]
