# Generated by Django 5.0 on 2024-01-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_product_admin_field_price1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high_priority',
            field=models.BooleanField(default=False),
        ),
    ]
