# Generated by Django 5.0 on 2024-01-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_product_high_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Description of product', max_length=150),
        ),
    ]
