# Generated by Django 5.0 on 2024-02-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
