# Generated by Django 5.0 on 2024-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EORLogging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
