# Generated by Django 5.0 on 2025-06-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EORLogging', '0003_alter_logentry_user'),
        ('Products', '0008_remove_product_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='details',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='product_name',
        ),
        migrations.AddField(
            model_name='logentry',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='logentry',
            name='username_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_category',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
