# Generated by Django 5.0 on 2025-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EORLogging', '0004_remove_logentry_details_remove_logentry_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
